
# python ../frd2vtu/frd2vtu.py shell6.frd

t1:
	python ../frd2vtu/frd2vtu.py pret4.frd

t2:
	python ../frd2vtu/frd2vtu.py planestrain.frd

t3:
	python ../frd2vtu/frd2vtu.py concretebeam.frd

t4:
	python ../frd2vtu/frd2vtu.py mohr1.frd

t5:
	python ../frd2vtu/frd2vtu.py mohr2.frd

t6:
	python ../frd2vtu/frd2vtu.py     zerovel.frd

t7:
	python ../frd2vtu/frd2vtu.py   ball.frd

t8:
	python ../frd2vtu/frd2vtu.py  simplebeampipe5.frd

t9:
	python ../frd2vtu/frd2vtu.py  simplebeam.frd

t10:
	python ../frd2vtu/frd2vtu.py shell7.frd

all: t1 t2 t3 t4 t5 t6 t7 t8 t9 t10