name: Run Tests

on:
    push:
        tags:
          - "v*.*.*"
        branches: [ main ]
    pull_request:
        branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" , "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Xvfb and OpenGL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgl1 libgl1-mesa-dri
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
    
    - name: Run tests with Xvfb
      run: |
        xvfb-run --auto-servernum pytest test/ --cov=frd2vtu
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
